/* Visitor approval in a phone-size browser: watchman asks, resident answers, gate screen updates; guest passes. Run: node tests/e2e-gate.js . outdir */
const { chromium, devices } = require('playwright'); const { create } = require('./gas'); const http = require('http'), fs = require('fs'), path = require('path');
const REPO = process.argv[2], OUT = process.argv[3]; fs.mkdirSync(OUT, { recursive: true });
const G = create({ file: path.join(REPO, 'apps-script/Code.gs') }); G.x.setup(); G.x.addCommittee();
G.sheets.users.rows.forEach((r, i) => { if (i && ['secretary', 'watchman'].includes(r[0])) r[3] = 'pw-' + r[0] + '1'; });
const PASS = { '101': '123456x', '102': '123456x', watchman: 'pw-watchman1x', secretary: 'pw-secretary1x' };
[['101', '123456'], ['102', '123456'], ['watchman', 'pw-watchman1'], ['secretary', 'pw-secretary1']].forEach(([u, p]) => { const t = G.call({ a: 'login', u, p }).token; G.call({ token: t, a: 'pw', password: p + 'x' }); });
G.sheets.users.rows.forEach((r, i) => { if (i) { r[6] = r[0] + '@example.com'; r[7] = 'yes'; } });
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.webp': 'image/webp', '.png': 'image/png', '.woff2': 'font/woff2', '.woff': 'font/woff', '.webmanifest': 'application/manifest+json' };
const srv = http.createServer((q, s) => { let p = q.url.split('?')[0]; if (p === '/') p = '/index.html'; const f = path.join(REPO, 'public', p); if (!fs.existsSync(f) || fs.statSync(f).isDirectory()) { s.writeHead(404); return s.end(); } s.writeHead(200, { 'Content-Type': MIME[path.extname(f)] || 'application/octet-stream' }); fs.createReadStream(f).pipe(s); }).listen(8767);
let ok = 0, bad = 0; const check = async (n, fn) => { try { await fn(); ok++; console.log('  ok   ' + n); } catch (e) { bad++; console.log('  FAIL ' + n + '\n       ' + String(e.message).split('\n')[0]); } };
async function session(b, who) { const ctx = await b.newContext({ ...devices['Pixel 7'], serviceWorkers: 'block' }), p = await ctx.newPage(); p.errors = [];
  p.on('pageerror', e => p.errors.push(String(e))); p.on('dialog', d => d.accept());
  p.delay = 0; await p.route('https://script.google.com/**', async r => { if (p.delay) await new Promise(z => setTimeout(z, p.delay)); await r.fulfill({ contentType: 'application/json', body: G.ctx.doPost({ postData: { contents: r.request().postData() } }).s }); });
  await p.route('https://www.gstatic.com/**', r => r.abort());
  await p.goto('http://localhost:8767/'); await p.selectOption('#em', who); await p.fill('#pw', PASS[who]); await p.click('#in'); await p.waitForSelector('nav button[data-t]'); return p; }
const go = async (p, t) => { await p.click('#hb'); await p.waitForTimeout(350); await p.click(`nav button[data-t="${t}"]`); await p.waitForSelector('#m:not([aria-busy])'); await p.waitForTimeout(300); };
const fresh = p => p.evaluate(() => { SNAP = null; DIRTY = true; dropCache(); });
const txt = p => p.locator('#m').innerText();
(async () => { const b = await chromium.launch();
  const w = await session(b, 'watchman');
  await check('watchman sees only Visitors and Contacts, opens on Visitors', async () => { const t = await w.locator('nav').innerText(); if (/Payments|Expenses|Complaints|Home/.test(t) || !/Visitors/.test(t) || !/Contacts/.test(t)) throw new Error(t); if (!/Record a visitor/i.test(await txt(w))) throw new Error('not on visitors'); });
  const r = await session(b, '101');
  await go(r, 'vis');
  await check('resident saves the gate phone number', async () => { await r.fill('#fph', '98480 55555'); await r.click('#fphs'); await r.waitForTimeout(500); if (G.x.read_('flats')[0].phone !== '98480 55555') throw new Error(JSON.stringify(G.x.read_('flats')[0])); });
  await check('watchman asks Flat 101 to approve', async () => { await w.fill('#vnm', 'Courier Ramu'); await w.selectOption('#vfl', '101'); await w.fill('#vpu', 'Delivery / courier'); await w.click('#vask'); await w.waitForTimeout(800);
    const t = await txt(w); if (!/Waiting for an answer · 1/i.test(t) || !/Courier Ramu → Flat 101/.test(t)) throw new Error(t.slice(0, 300));
    if (!G.pushes.some(x => /Visitor at the gate/.test(x.t) && x.to.user === '101' && x.ex.type === 'visit')) throw new Error('no alert'); });
  await w.screenshot({ path: OUT + '/gate-waiting.png', fullPage: false });
  await check('resident Home shows "At the gate now" with Approve / Deny / Leave at gate', async () => { await fresh(r); await go(r, 'dash'); const t = await txt(r); if (!/At the gate now/i.test(t) || !/Courier Ramu/.test(t)) throw new Error(t.slice(0, 300));
    if (!(await r.locator('[data-vdec$=":gate"]').count())) throw new Error('no leave-at-gate for delivery'); });
  await r.screenshot({ path: OUT + '/resident-home.png', fullPage: false });
  await check('resident taps Approve', async () => { await r.locator('[data-vdec$=":approve"]').first().click(); await r.waitForTimeout(800); const v = G.x.read_('visitors').find(x => x.name === 'Courier Ramu'); if (v.status !== 'approved' || v.decided_by !== '101') throw new Error(JSON.stringify(v)); });
  await check('watchman screen turns to "Let in" by itself within ~5 seconds', async () => { await w.waitForFunction(() => /Let in: Courier Ramu/.test(document.querySelector('#m').innerText), null, { timeout: 9000 }); });
  await w.screenshot({ path: OUT + '/gate-approved.png', fullPage: false });
  await check('no answer after 3 minutes shows Call Flat 101 with the saved number', async () => {
    await w.fill('#vnm', 'Guest Late'); await w.selectOption('#vfl', '101'); await w.click('#vask'); await w.waitForTimeout(800);
    const v = G.x.read_('visitors').find(x => x.name === 'Guest Late'); const sh = G.sheets.visitors, H = G.x.TABLES.visitors, row = sh.rows[v.__r - 1];
    const d = new Date(Date.now() - 4 * 60000), hm = String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0'); row[H.indexOf('created_at')] = "'" + v.visit_on + ' ' + hm; row[H.indexOf('created_at')] = v.visit_on + ' ' + hm; G.x.clearCache();
    await fresh(w); await go(w, 'vis'); const href = await w.locator('a.call', { hasText: 'Call Flat 101' }).getAttribute('href'); if (href !== 'tel:9848055555') throw new Error(href);
    if (!(await w.locator('[data-vagain]').count())) throw new Error('no ask again'); });
  await check('SPEED: with Google taking 2.5 s, every gate save shows on screen in under 0.5 s', async () => {
    await fresh(w); await go(w, 'vis'); w.delay = 2500; const t0 = Date.now();
    await w.fill('#vnm', 'Speed Test'); await w.selectOption('#vfl', '101'); await w.click('#vask');
    await w.waitForFunction(() => /Speed Test → Flat 101/.test(document.querySelector('#m').innerText), null, { timeout: 2000 }); const t1 = Date.now() - t0;
    const t2s = Date.now(); await w.fill('#vnm', 'Speed Two'); await w.selectOption('#vfl', '102'); await w.click('#vsv');
    await w.waitForFunction(() => /Speed Two/.test(document.querySelector('#m').innerText), null, { timeout: 2000 }); const t2 = Date.now() - t2s;
    w.delay = 0; await w.waitForTimeout(6000);
    if (!G.x.read_('visitors').some(x => x.name === 'Speed Test' && x.status === 'waiting')) throw new Error('not saved in background');
    console.log('       ask flat: ' + t1 + ' ms, save without asking: ' + t2 + ' ms (Google itself: 2500 ms)'); if (t1 > 600 || t2 > 600) throw new Error('too slow: ' + t1 + ' / ' + t2); });
  await check('resident answer is instant too', async () => { await fresh(r); await go(r, 'dash'); r.delay = 2500; const t0 = Date.now(); await r.locator('.card', { hasText: 'Speed Test' }).locator('[data-vdec$=":deny"]').click();
    await r.waitForFunction(() => !/Speed Test/.test(document.querySelector('#m').innerText), null, { timeout: 2000 }); const t = Date.now() - t0; r.delay = 0; await r.waitForTimeout(3500);
    console.log('       resident Deny: ' + t + ' ms'); if (!G.x.read_('visitors').some(x => x.name === 'Speed Test' && x.status === 'denied')) throw new Error('not saved'); });
  await check('gate sees the Deny without reloading', async () => { await w.waitForFunction(() => /Do not let in: Speed Test/.test(document.querySelector('#m').innerText), null, { timeout: 9000 }); });
  await check('resident makes a guest pass and gets a 6-digit code', async () => { await go(r, 'vis'); await r.fill('#pnm', 'Mother'); await r.click('#psv'); await r.waitForTimeout(1500); await go(r, 'vis'); const t = await txt(r); const m = /Mother[\s\S]{0,200}?\b(\d{6})\b/.exec(t); if (!m) throw new Error(t.slice(0, 400)); r.code = m[1]; });
  await r.screenshot({ path: OUT + '/resident-pass.png', fullPage: false });
  await check('watchman enters the code and lets Mother in; pass is used', async () => { await fresh(w); await go(w, 'vis'); await w.fill('#gpc', r.code); await w.click('#gpck'); await w.waitForSelector('#gplet'); await w.click('#gplet'); await w.waitForTimeout(800);
    const v = G.x.read_('visitors').find(x => x.name === 'Mother'); if (!v || v.status !== 'pre_approved') throw new Error(JSON.stringify(v)); await w.fill('#gpc', r.code); await w.click('#gpck'); await w.waitForTimeout(500); if (!/not valid/.test(await w.locator('#gpres').innerText())) throw new Error('code reusable'); });
  await check('always-allowed person appears at the gate and is let in with one tap', async () => { await r.fill('#pnm', 'Lakshmi'); await r.fill('#ppu', 'Domestic help'); await r.selectOption('#pkd', 'always'); await r.click('#psv'); await r.waitForTimeout(800);
    await fresh(w); await go(w, 'vis'); await w.locator('[data-vall]').first().click(); await w.waitForTimeout(800); if (!G.x.read_('visitors').some(x => x.name === 'Lakshmi' && x.status === 'always')) throw new Error('not saved'); });
  await check('always-allowed pass has no end date, so it still works tomorrow', async () => { const g = G.x.read_('guest_passes').find(x => x.name === 'Lakshmi'); if (g.valid_to) throw new Error('ends on ' + g.valid_to); });
  await check('Always allowed list: All flats by default, choose one flat, back to All after the app returns from background', async () => {
    const id = G.call({ token: G.call({ a: 'login', u: '102', p: '123456x' }).token, a: 'write', t: 'guest_passes', op: 'insert', payload: { name: 'Milk Ravi', purpose: 'Milk', kind: 'always' }, filters: [] }).id;
    await fresh(w); await go(w, 'vis'); if (await w.inputValue('#alf') !== '') throw new Error('not All by default');
    const card = () => w.locator('h2:has-text("Always allowed") + .card').innerText();
    let t = await card(); if (!/Lakshmi/.test(t) || !/Milk Ravi/.test(t)) throw new Error('All should list both: ' + t);
    await w.selectOption('#alf', '102'); await w.waitForTimeout(300); t = await card(); if (/Lakshmi/.test(t) || !/Milk Ravi/.test(t)) throw new Error('flat 102 only: ' + t);
    await fresh(w); await go(w, 'vis'); if (await w.inputValue('#alf') !== '102') throw new Error('choice lost while still using the app');
    await w.evaluate(() => { Object.defineProperty(document, 'visibilityState', { value: 'visible', configurable: true }); document.dispatchEvent(new Event('visibilitychange')); }); await w.waitForTimeout(400);
    if (await w.inputValue('#alf') !== '') throw new Error('not reset to All'); });
  await check('flat records its own visitor, the gate sees it, flat marks exit', async () => { await fresh(r); await go(r, 'vis'); await r.fill('#rvn', 'Neighbour Friend'); await r.click('#rvs'); await r.waitForTimeout(800);
    let t = await txt(r); if (!/Inside now · \d[\s\S]*Neighbour Friend/i.test(t)) throw new Error(t.slice(0, 300));
    await fresh(w); await go(w, 'vis'); if (!/Neighbour Friend[\s\S]{0,200}Entered by flat/.test(await w.locator('.tbl').first().innerText())) throw new Error('gate does not see it');
    await r.locator('.card', { hasText: 'Neighbour Friend' }).locator('[data-vout]').first().click(); await r.waitForTimeout(800);
    if (!G.x.read_('visitors').find(x => x.name === 'Neighbour Friend').out_time) throw new Error('exit not saved'); });
  await check('register shows the approval status', async () => { const t = await w.locator('.tbl').first().innerText(); if (!/Approved/.test(t) || !/Pre-approved/.test(t) || !/Always allowed/.test(t)) throw new Error(t.slice(0, 400)); });
  const r2 = await session(b, '102'); await go(r2, 'vis');
  await check('Flat 102 sees none of Flat 101\'s visitors, passes or phone', async () => { const t = await txt(r2); if (/Ramu|Mother|Lakshmi|98480/.test(t)) throw new Error('leak'); });
  const s = await session(b, 'secretary'); await go(s, 'vis');
  await check('Association sees gate phone numbers and active passes (no codes)', async () => { const t = await s.locator('#m').innerHTML(); if (!/98480 55555/.test(t)) throw new Error('no phone'); if (r.code && t.includes(r.code)) throw new Error('code shown'); });
  for (const [n, p] of [['watchman', w], ['101', r], ['102', r2], ['secretary', s]]) await check('no page errors: ' + n, async () => { const x = await txt(p); if (p.errors.length) throw new Error(p.errors.join(' | ')); if (/1899|NaN|undefined|Invalid Date/.test(x)) throw new Error('bad value'); const sw = await p.evaluate(() => [document.documentElement.scrollWidth, innerWidth]); if (sw[0] > sw[1] + 1) throw new Error('sideways ' + sw); });
  console.log('\n' + ok + ' passed, ' + bad + ' failed'); await b.close(); srv.close(); process.exit(bad ? 1 : 0);
})().catch(e => { console.error(e); process.exit(2); });
